language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install PyVCF
  - pip install requests
  - pip install PyYAML
install: true
script:
  - python3 -m unittest discover -v
  - prove --recurse --verbose
